[tool.poetry]
name = "pyobs-gui"
version = "0.16.0"
description = "A remote GUI for pyobs"
authors = ["Tim-Oliver Husser <thusser@uni-goettingen.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
colour = "^0.1"
PyQt5 = "^5.13"
matplotlib = "^3.4"
qfitswidget = "^0.8"
qasync = "^0.22"
pyobs-core = "^0.16.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pre-commit = "^2.16.0"
PyQt5-stubs = "^5.15.2"
sphinx-rtd-theme = "^1.0.0"
Sphinx = "^4.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py39']
